# Découpage d'une chaine de caractère (Slicing)
college = "college bois de bologne "
print(college[0])
print(college[8])
print(college[20])
print(college[-1])
print(college[-2])
print(college[-15],college[4])
print(college[8:-11])
print(college[8:12])
print(college[16:23])
print(college[-7:0])
print(college[0:20])
print(college[0:20:2])
print(len(college))
print(college[::-1])
print(college[:])
# print(college[start:end:step])

